// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwL9JvHP1DRi5kdlmIkebcUAt5BawPuJU',
    appId: '1:1075945858056:web:f42565312604274e469dbd',
    messagingSenderId: '1075945858056',
    projectId: 'todo-app-1c3cc',
    authDomain: 'todo-app-1c3cc.firebaseapp.com',
    storageBucket: 'todo-app-1c3cc.appspot.com',
    measurementId: 'G-4N3J9KJDE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8xNgf8uQwzTK-0QDhOPYb39DS_GKXy5Y',
    appId: '1:1075945858056:android:67c085aae2b3ae77469dbd',
    messagingSenderId: '1075945858056',
    projectId: 'todo-app-1c3cc',
    storageBucket: 'todo-app-1c3cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh-iPbTbq0FHmPljCYVbV77Bhyz3ED6Fc',
    appId: '1:1075945858056:ios:5e35377504d907e2469dbd',
    messagingSenderId: '1075945858056',
    projectId: 'todo-app-1c3cc',
    storageBucket: 'todo-app-1c3cc.appspot.com',
    iosClientId: '1075945858056-jn9b61enqrevbt2j8u9d7n65ltkpves9.apps.googleusercontent.com',
    iosBundleId: 'com.example.vtechTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh-iPbTbq0FHmPljCYVbV77Bhyz3ED6Fc',
    appId: '1:1075945858056:ios:5e35377504d907e2469dbd',
    messagingSenderId: '1075945858056',
    projectId: 'todo-app-1c3cc',
    storageBucket: 'todo-app-1c3cc.appspot.com',
    iosClientId: '1075945858056-jn9b61enqrevbt2j8u9d7n65ltkpves9.apps.googleusercontent.com',
    iosBundleId: 'com.example.vtechTodo',
  );
}
